### ISSUE TITLE
Principle 1 says don't use "please", but the json examples are polite with LLM

### ISSUE THREAD

**Issue by mst272** [VILA-Lab/ATLAS#1]
Is Principle 1 a negative collection?

**Comment by szq0214** [comment]
Hi @mst272, thank you for your interest in this work. It wouldn't be accurate to categorize P1 as negative, considering it does offer a marginal improvement. However, when compared to other principles, it certainly doesn't exhibit the same level of effectiveness, as shown in Figures 4 and 8.

**Comment by szq0214** [comment]
> Is Principle 1 a negative collection?

Hi @mst272, initially, the repository contained instructions before the principles for P-1, and other instructions are after the principles, we are correcting this and providing both of them. Sorry for the confusion.
