### ISSUE TITLE
Mistake in graphic?

### ISSUE THREAD

**Issue by krabina** [VILA-Lab/ATLAS#7]
The graphic shows in "User Iteraction and Engagement "P21" as "Style-Consistency. But P21 is "Detailed Writing" in Specificity and Information and also in the tables in the paper.

If 21 was referenced from two sections, it should be "Detailed Writing" in both. Otherwise it is unclear what "Style-Consistency" is and how it would be different from 22 "Preserve-Style"

**Comment by szq0214** [comment]
Hi @krabina, thanks very much for pointing this out, we have corrected it on github by removing P21 in "User Interaction and Engagement" and moving P15 in this category.
